apiVersion: v1
kind: Service
metadata:
  name: occ-payment-service
  labels:
    name: occ-payment-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30039
      name: http  
  selector:
    name: occ-payment