apiVersion: v1
kind: Service
metadata:
  name: occ-shop-service
  labels:
    name: occ-shop-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30035
      name: http 
  selector:
    app: occ-shop
